### ISSUE TITLE
Cannot connect to host storage.googleapis.com:443

### ISSUE THREAD

**Issue by urosbmx** [nadimkobeissi/mkbsd#58]
When I trigner script i recive this error

`Error: Cannot connect to host storage.googleapis.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]`

**Comment by mdragoss** [comment]
change to `async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(verify_ssl=False))`

**Comment by urosbmx** [comment]
Now it's working, thanks 👍
